name: Build and Push to ACR

on:
  push:
    branches:
      - master  

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: MyProjectASP.azurecr.io
        username: ${{ secrets.MyProjectASP }}
        password: ${{ secrets.l6xU/3UM+F/yo8piV9lYNZMrDLRswVY9xHegcYqYbb+ACRDBdJ1d }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: MyProjectASP.azurecr.io/myapp:latest
